services:
  isaac-sim:
    image: nvcr.io/nvidia/isaac-sim:5.1.0
    container_name: isaac-sim
    # platform: linux/amd64
    entrypoint: bash
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
    network_mode: host
    volumes:
      - ~/docker/isaac-sim/cache/main:/isaac-sim/.cache:rw
      - ~/docker/isaac-sim/cache/computecache:/isaac-sim/.nv/ComputeCache:rw
      - ~/docker/isaac-sim/logs:/isaac-sim/.nvidia-omniverse/logs:rw
      - ~/docker/isaac-sim/config:/isaac-sim/.nvidia-omniverse/config:rw
      - ~/docker/isaac-sim/data:/isaac-sim/.local/share/ov/data:rw
      - ~/docker/isaac-sim/pkg:/isaac-sim/.local/share/ov/pkg:rw
    user: "1234:1234"
    stdin_open: true
    tty: true
    restart: "no"
